### ISSUE TITLE
The Background video do not start again when it finish to reproduce.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#1]
Description: 
The background videos do not start again when they finished playing, this kind of background videos should start again every time they finished playing. 
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the components section.
3. Expand the Banners folder
4. Click on the edit button of the “Images“  component.
5. Go to the “Media Banner Section” 
6. Select in the “Display Media Selector” the video option.
7. In the Video Background upload a video.
8. Click on the “Save and Close” button
9. Check the preview of the page.
 
CURRENT RESULT: 
==================== 
The video only reproduces 1 time and then stays freeze.
https://www.screencast.com/t/qirKwXlfLEO 
 
EXPECTED RESULT: 
==================== 
The video should starts again every time it finish of reproducing.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Unable to reproduce in current version

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13, issue is not reproduced in the new crafter version.
