### ISSUE TITLE
The user can not continue navigating through the Crafter Studio when the notification message of “Is not a valid time format” is closed in the classes section.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#10]
Description: 
When the user enters an invalid time format and closed the Notification message the Crafter Studio freezes and the user can not continue using it.
 
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter Studio with the Fitness site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Home“  page.
4.Go to the Main Content Section, on the Page sections.
5. Select the Classes section and click on the edit button.
6. Select 1 class and click on the edit button.
7. In the Content section, set an invalid Start TIme (eg 14:00 pm)
8. Click on the Ok button of the notification message.    
9. Try to continue navigating through the crafter Studio.
 
*Note: Same behavior happens in the footer section.

CURRENT RESULT: 
==================== 
The notification modal gets closed, but when  the modal fade the web site stay blocked(like if a modal is open) and user can not continue navigating through the Crafter Studio. 
https://www.screencast.com/t/wz0XX93Xt 
 
EXPECTED RESULT: 
==================== 
The notification modal gets closed successfully, and the user should be able to continue navigating through the Crafter Studio.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed in the current version of crafter

**Comment by juacamar** [comment]
Bug is not reproduced in the last version of crafter.
