### ISSUE TITLE
The application is missing the option to add sunday in the days list, to add classes on sundays.   

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#11]
Description: 
The application is missing an option to add classes on sundays. 

-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Home“  page.
4.Go to the Main Content Section, on the Page sections.
5. Select the Classes section and click on the edit button.
6. On the Items list, select 1 class and click on the edit button.
7. On the “Class Days” click on the “Add Another” button.
8. Try to select Sundays in the day selector.
 
 
CURRENT RESULT: 
==================== 
The application is missing an option to add classes on sundays. 
https://www.screencast.com/t/LX3NGlhB4s 
 
EXPECTED RESULT: 
==================== 
The application should have an option to add classes on sundays.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
