### ISSUE TITLE
The application is displaying an error when the Workout classes section does not contain any class. 

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#12]
Description: The application is displaying an error when the Workout classes section does not contain any class. 
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Home“  page.
4.Go to the Main Content Section.
5. On the page section, select the Classes section and click on the edit button.
6. On the Items list, delete all classes or verified any class is in the list.
7. Click on the Save and Close Button.
8. Check in the preview of the site, the workout classes section.  
 
CURRENT RESULT: 
==================== 
The application displays an error when the “Classes” section does not have any configured class.
https://www.screencast.com/t/G8h0lS3z 
 
EXPECTED RESULT: 
==================== 
The application should not display any error message when the “Classes” section does not have any configured class.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
