### ISSUE TITLE
The application is displaying always the same background image for the configured workout classes although the user set a different background image.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#13]
Description: The application is displaying always the same background image for the configured workout classes although the user set a different background image.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Home“  page.
4.Go to the Main Content Section.
5. On the page section, select the Classes section and click on the edit button.
6. On the Items list, select “Add” button
7. Select Create New - items Source
8. Select Component - Catalog Item.
9. Fill Out all the parameters
10. In the Class image, add an image. 
11. Click on the Save and Close Button.
12. Check in the preview of the site, the workout classes section.  
 
 
CURRENT RESULT: 
==================== 
The application displays a different workout class background image than the one that user set for that class.
 https://www.screencast.com/t/xH3Lzree96
 
EXPECTED RESULT: 
==================== 
The application should display the workout class background image that the user set for that class.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
