### ISSUE TITLE
The application does not save the created items(class-item,price-item) in the correct Crafter Studio Folder.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#14]
Description: 
When the user create a new component of the types (class-item,price-item) the application does not save this components it the respective folder.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Home“  page.
4.Go to the Main Content Section.
5. On the page section, select the Classes section and click on the edit button.
6. On the Items list, select “Add” button
7. Select Create New - items Source
8. Select Component - Catalog Item.
9. Fill Out all the parameters e.g all with class1
10. In the Class image, add an image. 
11. Click on the Save and Close Button.
12. Repeat steps from 1 to 4
13. On the page section, select the Prices section and click on the edit button.
14. On the Items list, select “Add” button
15. Select Create New - items Source
16. Select Component - Catalog Item price.
17. Fill Out all the parameters e.g all with itemprice1
18. Add some services.
19. Click on the Save and Close Button.
20. Review the Crafter Studio Folders.
 
 
CURRENT RESULT: 
==================== 
The application does not save the created items(class-item,price-item) in the correct Crafter Studio Folder.
https://www.screencast.com/t/TnowGPCM 
 
EXPECTED RESULT: 
==================== 
The application should save the created items(class-item,price-item) in the correct Crafter Studio Folder of each item.

**Comment by LorenzoRodriguezRivetlogic** [comment]
The same is used for classes and prices, so it's not possible to know which type of item is being used.

**Comment by juacamar** [comment]
Bug closed as  won't fix.
