### ISSUE TITLE
The application does not display the Prices section properly arranged when the “Prices items” have different amount of services added.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#17]
Description:
 The application does not display the Prices section properly arranged when the “Prices items” have different amount of services added.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Prices“ page section.
4. On the items list, add 5 items with the next properties.
     Item 1: Fill all the fields and add 5 Services.
     Item 2: Fill all the fields and add 13 Services.
     Item 3: Fill all the fields and add 5 Services.
     Item 4 :Fill all the fields and add 3 Services.
     Item 5 :Fill all the fields and add 13 Services.
5. Click on the Save and Close Button.
6. Go to the page preview and check the Prices section
 
 
CURRENT RESULT: 
==================== 
The application displays all the configured items but they are not arranged properly.
https://screencast.com/t/zSib7jBnwblm 
 
EXPECTED RESULT: 
==================== 
The application should display all the configured items properly arranged.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
