### ISSUE TITLE
The application is displaying an error when an item of the prices section does not contain any service. 

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#18]
Description: 
The application is displaying an error when an item of the prices section does not contain any service. 
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Home“  page.
4.Go to the Main Content Section.
5. On the page section, select the Prices section and click on the edit button.
6. On the Items list, click on the add button and select the “Create New -items Source” option.
7. Fill Out all the fields, but do not add any service.  
8. Click on the Save and Close Button.
9. Check in the preview of the site, the prices section.  
 
CURRENT RESULT: 
==================== 
The application displays an error when the “Prices” section does not have any configured service in the price-item.
https://www.screencast.com/t/b6rFzvQLQ 
 
EXPECTED RESULT: 
==================== 
The application should not display any error message when the “Price” section does not have any configured service in the price-item.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
