### ISSUE TITLE
The application does not display the configured background image in the “Testimonials” section.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#19]
Description: 
The application allow the user to set a background image in the Crafter Studio, but the image is not displayed in the site.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Home“  page.
4. Go to the Main Content Section.
5. On the page section, select the “Quotes” section and click on the edit button.
6. In the Content section, add a new “Image Background”.
7. Click on the Save and Close Button.
8. Check the testimonials section in the preview of the site.
 
CURRENT RESULT: 
==================== 
The application do not display the background image that the user set for the testimonials section.
https://screencast.com/t/HMByX1pIY 
 
EXPECTED RESULT: 
==================== 
The application should display the background image that the user set for the testimonials section.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
