### ISSUE TITLE
When the user adds new "navigation menu items", this are not redirecting to the specified section.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#2]
Description: 
When the user adds new navigation items and click on them, they do not redirect to the specific page section.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the components section.
3. Expand the Header folder
4. Click on the edit button of the “Header“  component.
5. Go to the “Navigation Menu” Section
6. Add 2 new Navigation menu items.
	e.g Prices
	E.g Testimonials
7. Click on the “Save and Close” button
8. Check the preview of the page.
9. Click on the new items created.

*Note, Same happens when the user tries to change Button Section Link in the "about" section.
 (button do not redirect to Classes, prices and Testimonials sections. )

 
CURRENT RESULT: 
==================== 
The new "navigation menu items" are not redirecting to the specified section.
https://www.screencast.com/t/b1NyCqV7A 
 
EXPECTED RESULT: 
==================== 
The new "navigation menu items" should redirect to the specified section.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
