### ISSUE TITLE
 The testimonials characters limit should be shorter, so the page is  always displayed properly.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#20]
Description:
The testimonial character limit is 100.000, so when the user writes a larger testimonial the page is not displayed properly.
 
-Env:
Using the Fitness Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 

REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the components section.
3. Click on the edit button of the Quotes.
4. In the Quotes section Add a new Quote.
Eg. Description: Field At least 30.000 characters 
       Author Full Name: John A.
      Author Profession: Engineer 	
4. Click on the Save and Close Button.
5. Go to the Page preview the testimonial section.
 
*Video
https://www.screencast.com/t/RUaORIboKji9 
 
CURRENT RESULT: 
==================== 
The application displays the testimonial properly but, when the user selects another shorter testimonial the page design is not displayed properly
 
EXPECTED RESULT: 
==================== 
 The testimonials characters limit should be shorter, so the page is  always displayed properly.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build c684dfc.
