### ISSUE TITLE
The “Sign Up Now” button does not perform any action when the user clicks on it.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#21]
-Title:  The “Sign Up Now” button does not perform any action. 
 
-Env:
Using the Fitness Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
Description:  The “Sign Up Now” button does not perform any action, also the Crafter Studio does not have any option to configure an action to the button. 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site preview, go to the Prices section.
3. Click on the “Sign Up Now” button on some of the items.
 
CURRENT RESULT: 
==================== 
The “Sign Up Now” button does not perform any action when the user clicks it. 
 
EXPECTED RESULT: 
==================== 
The “Sign Up Now” button should perform an action when the user clicks it.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build e51f84f.
