### ISSUE TITLE
The application does not allow to view the trainers properties(name, social links) on Safari on apple devices.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#22]
Description: 
 When the user clicks on a trainer to view its properties, it is immediately redirected to a social link.

-Env:
Using the Fitness Blueprint
Device: Iphone 7 
	      Ipod 5 
IOS:10.3
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site preview, go to the Trainers section.
3. Click on a Trainer.
 
CURRENT RESULT: 
==================== 
The application does not allow the user to check the trainers properties(name, social links) on Safari on Apple devices.
https://www.screencast.com/t/7S1PEev2yUzz
 
EXPECTED RESULT: 
==================== 
The application should display the trainer properties, when the user click in any area of the trainer-item(in the browser this is a hover).

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build c684dfc.
