### ISSUE TITLE
 The application does not allow the user to view the “Sign Up Now” button in the “Prices” section on Apple devices.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#23]
Description:  
When the user clicks on a price-item to view its properties nothing happen unless the user click where the hidden button is located.

-Env:
Using the Fitness Blueprint
Device: Iphone 7 
	  Ipod 5 
IOS:10.3
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site preview, go to the Prices section.
3. Click on a Price-item.
4. Click where the hidden button is located.
 
CURRENT RESULT: 
==================== 
The application does not allow the user to view the “Sign Up Now” button in the “Prices” section on Apple devices, unless the user click where the hidden button is located.
 https://www.screencast.com/t/i3Dm1BQTG 
 
EXPECTED RESULT: 
==================== 
The application should display the “sign Up Now” button properties, when the user clicks in any area of the price-item(in the browser this is a hover).

**Comment by LorenzoRodriguezRivetlogic** [comment]
FIxed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build c684dfc.
