### ISSUE TITLE
The Background images in the “Workouts” section are not displayed on Apple devices.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#24]
Description:  
When the user clicks on a workout-item the background image is not displayed.
 
-Env:
Using the Fitness Blueprint
Device: Iphone 7 
	  Ipod 5 
IOS:10.3
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site preview, go to the Workout section.
3. Click on a Workout-item.
 
CURRENT RESULT: 
==================== 
The Background images in the “Workouts” section are not displayed.
https://screencast.com/t/1j153XPmMM8h
https://www.screencast.com/t/Qtn92f8Jo0 on android background images are displayed.
 
EXPECTED RESULT: 
==================== 
The Background images in the “Workouts” section should be displayed.

**Comment by LorenzoRodriguezRivetlogic** [comment]
The images should be shown after a tap over the class, please retest.

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
