### ISSUE TITLE
The site is missing some quick links in the navigation menu. 

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#25]
Description: 
The site does not contain all the quick links for the site sections, the site should contain a quick link to (Classes, Prices and testimonials) sections.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the components section.
3. Check the preview of the page.
4. Review the quick link items.
 
CURRENT RESULT: 
==================== 
The "navigation menu" does not contains all the quick links for all the sections, according to the used template. 
Template Quick links: https://www.screencast.com/t/QNpthFTJ7kh 
 
EXPECTED RESULT: 
==================== 
The "navigation menu" should contains all the quick links for all the sections.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed. The header now have these options: Home, About, Trainers, Workouts, Prices, Testimonials

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build c684dfc.
