### ISSUE TITLE
The input fields in the “Sign Up Newsletter” section does not have any format validation.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#26]
Description:  
When the user fill out the inputs the application does not validate if the introduced data has the correct format for the field.
 
-Env:
Device: Macbook pro
Google Chrome Version 58.0.30.29.113
 
Device: Android 7.1.1 
Google Chrome Version 55.0.2883.79
Mozilla Firefox 53.0.2
 
Device: Iphone 7
Google Chrome Version 58.0.30.29.113
Safari IOS 10.3
 
STEPS: 
==================== 
Steps 
1. Open  the Fitness site.
2. Go to the “Newsletter” section.
3 Fill out the fields with the next text.
	Name: leave in blank 
	Email: juan.com
4.Click on the “Send Message” Button.
 
CURRENT RESULT: 
==================== 
The application allows the user to registered successfully by displaying a “Thanks for contact us and subscribed to our Newsletter service.” message, although some fields are with no data and the email has an incorrect format.
 
EXPECTED RESULT: 
==================== 
 The application should not allow the user to register, unless all the fields are filled out and have the correct format.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build d5c2bd0.
