### ISSUE TITLE
The button in the “about” section is not displayed properly when the text contains the maximum characters permitted.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#3]
Description: 
When the user type a longer name for the button in the overview section, this is not displayed properly.
 
-Env:
Using the Fitness Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the components section.
3. Expand the page-sections folder.
4. Click on the edit button of the Overview section.
5. On the “Link to Page Section” change the name of the button for one with 50 characters.
6. Click on the Save and Close Button.
7. Go to the Page preview the About section.
 
CURRENT RESULT: 
==================== 
 The button in the about section is not displayed properly.
https://www.screencast.com/t/KUtcLrMwa 
 
EXPECTED RESULT: 
==================== 
 The text of the button in the “About” section should have a shorter character limit, so the page is  always displayed properly.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
