### ISSUE TITLE
The “home” section is not displayed properly in mobile.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#33]
Description: 
The “home” section is not displayed properly in mobile.

-Env:
Device: Android 7.1.1 
Google Chrome Version 55.0.2883.79
Mozilla Firefox 53.0.2

Device: Iphone 7
Google Chrome Version 58.0.30.29.113
Safri 10.3
Firefox 7.2(2672)

STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. Review the site

CURRENT RESULT: 
==================== 
 The “home” section is not displayed properly in mobile.
https://www.screencast.com/t/hz6Dgfh0erG 

EXPECTED RESULT: 
==================== 
 The “home” section should be displayed properly in mobile.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build d0d3014.
