### ISSUE TITLE
The application does not display the trainers properly arranged when the "Trainer Description" has different amount of characters.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#4]
Description: 
When the “Trainer Description” of some trainers is full of characters, the “Trainer's” site section page does not arrange the trainers properly.
 
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Trainers“  page.
4. On the Trainer list, add 6 trainers with the next properties.
     Trainer 1: Fill all the fields and the “Trainer Description” with the maximum characters limit (350).
     Trainer 2 : Fill all the fields and the “Trainer Description” with 50 characters .
     Trainer 3 : Fill all the fields and the “Trainer Description” with 50 characters .
     Trainer 4 : Fill all the fields and the “Trainer Description” with 350 characters .
     Trainer 5 : Fill all the fields and the “Trainer Description” with 350 characters .
     Trainer 6 : Fill all the fields and the “Trainer Description” with 50 characters .
    
5. Click on the Save and Close Button.
6. Go to the page preview and check the trainers section
 
 
CURRENT RESULT: 
==================== 
The application displays all the configured trainers but they are not arranged properly.
https://www.screencast.com/t/yUP6qxEZ 
https://www.screencast.com/t/Ajsfr4bGU3x 
 
EXPECTED RESULT: 
==================== 
The application should display all the configured trainers properly arranged.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
