### ISSUE TITLE
The application displays an error message when the user does not configure any “Social Media Link” for a trainer.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#5]
Description:  
The application displays an error message when the user does not configure any “Social Media Link” for a trainer.

-Env.
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Trainers“  page.
4. On the Trainer list, add 1 trainer with the next properties.
     Trainer 1: Fill out all the Fields, but do not add any Social Media Link.
    5. Click on the Save and Close Button.
6. Go to the page preview and check the trainers section
 
 
CURRENT RESULT: 
==================== 
The application displays an error message when the user does not configure any “Social Media Link” for a trainer.
https://www.screencast.com/t/bxQEvK4XyM   
 
EXPECTED RESULT: 
==================== 
The application should not displays any error message when the trainers does not have any “Social Media Link” configured.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
