### ISSUE TITLE
The application is not cleaning the fields when a registration is made.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#6]
Description: 
The application is not cleaning the fields when a registration is made.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. Go to the “Newsletter” section.
3. Fill out all the fields
4. Click on the Send Message Button.
 
CURRENT RESULT: 
==================== 
The registration was done correctly, but the fields were not cleared after clicking the Send Message button.
https://screencast.com/t/ImxAmze1 
 
EXPECTED RESULT: 
==================== 
The registration was done correctly, but the fields should be cleared after clicking the send button button.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
