### ISSUE TITLE
The application allows to send a registration although any field is fulfilled.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#7]
Description:
The application allows the user to send a registration without filling out the, “Name” and “email” fields that should be required fields.
 
-Env:
Crafter Fitness Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. Go to the Newsletter section 
3. Leave in blank the Name and Email Fields.
4. Click on the “Send Message” Button.
 
 
CURRENT RESULT: 
==================== 
The application is displaying a “Successful” message.
https://screencast.com/t/qf6fUN8y 
 
EXPECTED RESULT: 
==================== 
The application should displays an error message or should not allow the user to click the send message button until all the required values of the newsletter are fulfilled.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
