### ISSUE TITLE
 The application should limit the type of components to be added for every specified section.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#8]
Description: 
The application allows the user to add any component in any page section.
-Env:
Crafter Fitness Blueprint
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the Page Section.
3. Click on the edit button of the “Home” page.
4. Go to the “Page Sections”
5. Select the “Trainers” option and click on the edit button.
6. Go to the trainer list section.
7. Click on the Add button.
8. Select the “Create New - Trainers Source” 
 
*Note change should be applied for all the sections.
 
CURRENT RESULT: 
==================== 
The application allows the user to add any type of component.
https://www.screencast.com/t/M021ft55P1Il 
 
EXPECTED RESULT: 
==================== 
The application should only allows the user to add the proper type of component for each specified section.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build e51f84f.
