### ISSUE TITLE
The application does not display the “Workout classes” properly arranged when the "Title Text or the Trainer Name" has different amount of characters.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-fitness#9]
Description: 
When the "Title Text or the Trainer Name" of some “Workout classes” is full of Workout classes properly.
 
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Fitness site.
2. On the site bar, locate the pages section.
3. Click on the edit button of the “Home“  page.\
4.Go to the Main Content Section, on the Page sections.
5. Select the Classes section and click on the edit button.
4. On the Items list, add 6 Classes with the next properties.
     Class 1: Fill all the fields and the “Title text” with the maximum characters limit (50).
     Class 2 : Fill all the fields and the “Title text” with 10 characters .
     Class 3 : Fill all the fields and the “Title text” with 50 characters .
     Class 4 : Fill all the fields and the “Title text” with 10 characters .
     Class 5 : Fill all the fields and the “Title text” with 10 characters .
     Class 6 : Fill all the fields and the “Title text” with 10 characters .
    
5. Click on the Save and Close Button.
6. Go to the page preview and check the Workouts section
 
 
CURRENT RESULT: 
==================== 
The application displays all the configured workouts classes but they are not arranged properly.
https://www.screencast.com/t/UBIqG3UZtgV
 
EXPECTED RESULT: 
==================== 
The application should display all the configured workouts classes properly arranged.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed fixed in build c557d13.
